roboptim::NagSolverNlpSparse Class Reference
roboptim::NagSolverNlpSparse Class Reference
Roboptim_solver
Nonlinear sparse solver.
#include <roboptim/core/plugin/nag/nag-nlp-sparse.hh>
Public Types
typedef NagSolverCommon
< EigenMatrixSparse > parent_t
typedef GenericLinearFunction
< EigenMatrixSparse > linearFunction_t
typedef
GenericNumericLinearFunction
< EigenMatrixSparse > numericLinearFunction_t
typedef
GenericDifferentiableFunction
< EigenMatrixSparse > differentiableFunction_t
typedef differentiableFunction_t nonlinearFunction_t
typedef problem_t::function_t function_t
typedef problem_t::vector_t vector_t
typedef problem_t::jacobian_t jacobian_t
Public Member Functions
NagSolverNlpSparse (const problem_t &pb)
virtual ~NagSolverNlpSparse ()
void solve ()
Solve the problem.
void setIterationCallback (callback_t callback)
const callback_t & callback () const
solverState_t & solverState ()
Static Public Attributes
static const int linearFunctionId = 0
static const int nonlinearFunctionId = 1
Detailed Description
Nonlinear sparse solver.
Minimize an arbitrary smooth function subject to constraints (which may include simple bounds on the variables, linear constraints and smooth nonlinear constraints) using a sequential quadratic programming (SQP) method. As many first derivatives as possible should be supplied by you; any unspecified derivatives are approximated by finite differences. It is not intended for large sparse problems.
See also:
http://www.nag.com/numeric/CL/nagdoc_cl23/html/E04/e04wdc.html
Member Typedef Documentation
typedef GenericDifferentiableFunction<EigenMatrixSparse> roboptim::NagSolverNlpSparse::differentiableFunction_t
typedef problem_t::function_t roboptim::NagSolverNlpSparse::function_t
typedef problem_t::jacobian_t roboptim::NagSolverNlpSparse::jacobian_t
typedef GenericLinearFunction<EigenMatrixSparse> roboptim::NagSolverNlpSparse::linearFunction_t
typedef differentiableFunction_t roboptim::NagSolverNlpSparse::nonlinearFunction_t
typedef GenericNumericLinearFunction<EigenMatrixSparse> roboptim::NagSolverNlpSparse::numericLinearFunction_t
typedef NagSolverCommon<EigenMatrixSparse> roboptim::NagSolverNlpSparse::parent_t
typedef problem_t::vector_t roboptim::NagSolverNlpSparse::vector_t
Constructor & Destructor Documentation
roboptim::NagSolverNlpSparse::NagSolverNlpSparse (const problem_t & pb) [explicit]
References roboptim::NagSolverCommon< EigenMatrixSparse >::initializeParameters().
roboptim::NagSolverNlpSparse::~NagSolverNlpSparse () [virtual]
Member Function Documentation
const callback_t& roboptim::NagSolverNlpSparse::callback () const [inline]
Referenced by roboptim::detail::usrfun().
void roboptim::NagSolverNlpSparse::setIterationCallback (callback_t callback) [inline]
void roboptim::NagSolverNlpSparse::solve ()
Solve the problem.
References roboptim::errorHandler(), roboptim::NagSolverCommon< EigenMatrixSparse >::updateParameters(), and roboptim::detail::usrfun().
solverState_t& roboptim::NagSolverNlpSparse::solverState () [inline]
Referenced by roboptim::detail::usrfun().
Member Data Documentation
const int roboptim::NagSolverNlpSparse::linearFunctionId = 0 [static]
const int roboptim::NagSolverNlpSparse::nonlinearFunctionId = 1 [static]