roboptim::NagSolverDifferentiable Class Reference
roboptim::NagSolverDifferentiable Class Reference
Roboptim_solver
Solver for C1 function with gradient computation, no constraint.
#include <roboptim/core/plugin/nag/nag-differentiable.hh>
Public Types
typedef Solver
< DifferentiableFunction,
boost::mpl::vector<> > parent_t
Public Member Functions
NagSolverDifferentiable (const problem_t &pb) throw ()
virtual ~NagSolverDifferentiable () throw ()
void solve () throw ()
Solve the problem.
void setIterationCallback (callback_t callback) throw (std::runtime_error)
const callback_t & callback () const throw ()
solverState_t & solverState () throw ()
Detailed Description
Solver for C1 function with gradient computation, no constraint.
Search for a minimum, in a given finite interval, of a continuous function of a single variable, using function and first derivative values. The method (based on cubic interpolation) is intended for functions which have a continuous first derivative (although it will usually work if the derivative has occasional discontinuities).
See also:
http://www.nag.com/numeric/CL/nagdoc_cl23/html/E04/e04bbc.html
Member Typedef Documentation
typedef Solver<DifferentiableFunction, boost::mpl::vector<> > roboptim::NagSolverDifferentiable::parent_t
Constructor & Destructor Documentation
roboptim::NagSolverDifferentiable::NagSolverDifferentiable (const problem_t & pb) throw () [explicit]
References DEFINE_PARAMETER.
roboptim::NagSolverDifferentiable::~NagSolverDifferentiable () throw () [virtual]
Member Function Documentation
const callback_t& roboptim::NagSolverDifferentiable::callback () const throw () [inline]
Referenced by roboptim::detail::nagSolverCallbackDifferentiable().
void roboptim::NagSolverDifferentiable::setIterationCallback (callback_t callback) throw (std::runtime_error) [inline]
void roboptim::NagSolverDifferentiable::solve () throw ()
Solve the problem.
References roboptim::detail::nagSolverCallbackDifferentiable().
solverState_t& roboptim::NagSolverDifferentiable::solverState () throw () [inline]
Referenced by roboptim::detail::nagSolverCallbackDifferentiable().