roboptim::NagSolverNlp Class Reference
roboptim::NagSolverNlp Class Reference
Roboptim_solver
Nonlinear solver.
#include <roboptim/core/plugin/nag/nag-nlp.hh>
Public Types
typedef NagSolverCommon
< EigenMatrixDense > parent_t
Public Member Functions
NagSolverNlp (const problem_t &pb)
virtual ~NagSolverNlp ()
void solve ()
Solve the problem.
void setIterationCallback (callback_t callback)
const callback_t & callback () const
solverState_t & solverState ()
Detailed Description
Nonlinear solver.
Minimize an arbitrary smooth function subject to constraints (which may include simple bounds on the variables, linear constraints and smooth nonlinear constraints) using a sequential quadratic programming (SQP) method. As many first derivatives as possible should be supplied by you; any unspecified derivatives are approximated by finite differences. It is not intended for large sparse problems.
See also:
http://www.nag.com/numeric/CL/nagdoc_cl23/html/E04/e04wdc.html
Member Typedef Documentation
typedef NagSolverCommon<EigenMatrixDense> roboptim::NagSolverNlp::parent_t
Constructor & Destructor Documentation
roboptim::NagSolverNlp::NagSolverNlp (const problem_t & pb) [explicit]
roboptim::NagSolverNlp::~NagSolverNlp () [virtual]
Member Function Documentation
const callback_t& roboptim::NagSolverNlp::callback () const [inline]
Referenced by roboptim::detail::objfun().
void roboptim::NagSolverNlp::setIterationCallback (callback_t callback) [inline]
void roboptim::NagSolverNlp::solve ()
Solve the problem.
References roboptim::detail::confun(), and roboptim::detail::objfun().
solverState_t& roboptim::NagSolverNlp::solverState () [inline]
Referenced by roboptim::detail::objfun().