roboptim::nag::detail Namespace Reference
roboptim::nag::detail Namespace Reference
Functions
static void solverCallback (Integer ROBOPTIM_DEBUG_ONLY(n), const double xc[], double *fc, Nag_Comm *comm)
Function Documentation
static void roboptim::nag::detail::solverCallback (Integer ROBOPTIM_DEBUG_ONLYn, const double xc[], double * fc, Nag_Comm * comm) [static]
References roboptim::nag::Simplex::callback(), and roboptim::nag::Simplex::solverState().
Referenced by roboptim::nag::Simplex::solve().