roboptim::detail Namespace Reference
roboptim::detail Namespace Reference
ROBOPTIM_CORE_CFSQP_PLUGIN_CHECK_GRADIENT.
Functions
static void nagSolverCallbackDifferentiable (double xc, double *fc, double *gc, Nag_Comm *comm)
static void usrfun (::Integer *status,::Integer n, const double x[],::Integer needf,::Integer nf, double f[],::Integer needg,::Integer leng, double g[], Nag_Comm *comm)
static void confun (::Integer *mode,::Integer ncnln,::Integer n,::Integer tdcj, const ::Integer[], const double x[], double ccon[], double cjac[],::Integer, Nag_Comm *comm)
static void objfun (::Integer *mode,::Integer n, const double x[], double *objf, double grad[],::Integer, Nag_Comm *comm)
static void nagSolverCallback (double xc, double *fc, Nag_Comm *comm)
Detailed Description
ROBOPTIM_CORE_CFSQP_PLUGIN_CHECK_GRADIENT.
Function Documentation
static void roboptim::detail::confun (::Integer * mode, ::Integer ncnln, ::Integer n, ::Integer tdcj, const ::Integer [], const double x[], double ccon[], double cjac[], ::Integer , Nag_Comm * comm) [static]
Referenced by roboptim::NagSolverNlp::solve().
static void roboptim::detail::nagSolverCallback (double xc, double * fc, Nag_Comm * comm) [static]
Referenced by roboptim::NagSolver::solve().
static void roboptim::detail::nagSolverCallbackDifferentiable (double xc, double * fc, double * gc, Nag_Comm * comm) [static]
References roboptim::NagSolverDifferentiable::callback().
Referenced by roboptim::NagSolverDifferentiable::solve().
static void roboptim::detail::objfun (::Integer * mode, ::Integer n, const double x[], double * objf, double grad[], ::Integer , Nag_Comm * comm) [static]
References roboptim::NagSolverNlp::callback().
Referenced by roboptim::NagSolverNlp::solve().
static void roboptim::detail::usrfun (::Integer * status, ::Integer n, const double x[], ::Integer needf, ::Integer nf, double f[], ::Integer needg, ::Integer leng, double g[], Nag_Comm * comm) [static]
References roboptim::NagSolverNlpSparse::callback(), roboptim::checkJacobian(), roboptim::NagSolverNlpSparse::linearFunctionId, and roboptim::NagSolverNlpSparse::nonlinearFunctionId.
Referenced by roboptim::NagSolverNlpSparse::solve().