roboptim::NagSolverDifferentiable Class Reference
roboptim::NagSolverDifferentiable Class Reference
Roboptim_solver
Solver for C1 function with gradient computation, no constraint.
#include <roboptim/core/plugin/nag/nag-differentiable.hh>
Public Types
typedef Solver< EigenMatrixDense > parent_t
typedef Function::argument_t argument_t
typedef Function::result_t result_t
typedef
DifferentiableFunction::gradient_t gradient_t
Public Member Functions
NagSolverDifferentiable (const problem_t &pb)
virtual ~NagSolverDifferentiable ()
void solve ()
Solve the problem.
void setIterationCallback (callback_t callback)
const callback_t & callback () const
solverState_t & solverState ()
Detailed Description
Solver for C1 function with gradient computation, no constraint.
Search for a minimum, in a given finite interval, of a continuous function of a single variable, using function and first derivative values. The method (based on cubic interpolation) is intended for functions which have a continuous first derivative (although it will usually work if the derivative has occasional discontinuities).
See also:
http://www.nag.com/numeric/CL/nagdoc_cl23/html/E04/e04bbc.html
Member Typedef Documentation
typedef Function::argument_t roboptim::NagSolverDifferentiable::argument_t
typedef DifferentiableFunction::gradient_t roboptim::NagSolverDifferentiable::gradient_t
typedef Solver<EigenMatrixDense> roboptim::NagSolverDifferentiable::parent_t
typedef Function::result_t roboptim::NagSolverDifferentiable::result_t
Constructor & Destructor Documentation
roboptim::NagSolverDifferentiable::NagSolverDifferentiable (const problem_t & pb) [explicit]
References DEFINE_PARAMETER.
roboptim::NagSolverDifferentiable::~NagSolverDifferentiable () [virtual]
Member Function Documentation
const callback_t& roboptim::NagSolverDifferentiable::callback () const [inline]
Referenced by roboptim::detail::nagSolverCallbackDifferentiable().
void roboptim::NagSolverDifferentiable::setIterationCallback (callback_t callback) [inline]
void roboptim::NagSolverDifferentiable::solve ()
Solve the problem.
References roboptim::detail::nagSolverCallbackDifferentiable().
solverState_t& roboptim::NagSolverDifferentiable::solverState () [inline]
Referenced by roboptim::detail::nagSolverCallbackDifferentiable().