roboptim::NagSolverNlp Class Reference
roboptim::NagSolverNlp Class Reference
Roboptim_solver
Non-linear solver.
#include <roboptim/core/plugin/nag/nag-nlp.hh>
Public Types
typedef Solver
< DifferentiableFunction,
boost::mpl::vector
< LinearFunction,
DifferentiableFunction > > parent_t
Public Member Functions
NagSolverNlp (const problem_t &pb) throw ()
virtual ~NagSolverNlp () throw ()
void solve () throw ()
Solve the problem.
void setIterationCallback (callback_t callback) throw (std::runtime_error)
const callback_t & callback () const throw ()
solverState_t & solverState () throw ()
Detailed Description
Non-linear solver.
Minimize an arbitrary smooth function subject to constraints (which may include simple bounds on the variables, linear constraints and smooth nonlinear constraints) using a sequential quadratic programming (SQP) method. As many first derivatives as possible should be supplied by you; any unspecified derivatives are approximated by finite differences. It is not intended for large sparse problems.
See also:
http://www.nag.com/numeric/CL/nagdoc_cl23/html/E04/e04wdc.html
Member Typedef Documentation
typedef Solver< DifferentiableFunction, boost::mpl::vector< LinearFunction, DifferentiableFunction> > roboptim::NagSolverNlp::parent_t
Constructor & Destructor Documentation
roboptim::NagSolverNlp::NagSolverNlp (const problem_t & pb) throw () [explicit]
roboptim::NagSolverNlp::~NagSolverNlp () throw () [virtual]
Member Function Documentation
const callback_t& roboptim::NagSolverNlp::callback () const throw () [inline]
Referenced by roboptim::detail::objfun().
void roboptim::NagSolverNlp::setIterationCallback (callback_t callback) throw (std::runtime_error) [inline]
void roboptim::NagSolverNlp::solve () throw ()
Solve the problem.
References roboptim::detail::confun(), and roboptim::detail::objfun().
solverState_t& roboptim::NagSolverNlp::solverState () throw () [inline]
Referenced by roboptim::detail::objfun().